import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from './LogoutBtn';
import { cookies } from 'next/headers';
import DarkMode from './DarkMode';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  // console.log('여긴가', session);

  const res = cookies().get('mode');
  console.log(res);

  return (
    <html lang="en">
      <body className={` ${inter.className} ${res && res.value == 'dark' ? 'dark-mode' : ''}`}>
        <div className="navbar">
          <Link href={'/'} className="logo">
            메모장
          </Link>
          <div className="util">
            <DarkMode modeVal={res && res.value} />
            {session ? (
              <span>
                {session.user.name} <LogoutBtn />
              </span>
            ) : (
              <LoginBtn />
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
